import type { Skill, SkillContext } from './registry.js';
import type { SkillResult } from '@tetherline/shared';

export const shareSkill: Skill = {
  name: 'share_explanation',
  description: 'Generate a shareable markdown snippet of the current explanation',
  async execute(context: SkillContext, _params: Record<string, string>): Promise<SkillResult> {
    const area = context.currentArea;

    const sections: string[] = [];
    sections.push(`## ${area?.name ?? 'Code Review Note'}`);
    if (area?.description) sections.push(area.description);
    sections.push('');

    // Add narration context from recent segments
    if (area?.narrationSegments?.length) {
      sections.push('### Key Points');
      for (const seg of area.narrationSegments.slice(0, 5)) {
        sections.push(`- ${seg.text}`);
      }
      sections.push('');
    }

    if (area?.affectedFiles?.length) {
      sections.push('### Files');
      for (const f of area.affectedFiles.slice(0, 10)) {
        sections.push(`- \`${f}\``);
      }
    }

    sections.push('');
    sections.push(`*Generated by Tetherline on ${new Date().toISOString().split('T')[0]}*`);

    const markdown = sections.join('\n');

    return {
      skillName: 'share_explanation',
      type: 'explanation',
      narration: 'I\'ve prepared a shareable summary. You can copy it to your clipboard.',
      visualPayload: {
        action: 'share_preview',
        markdown,
      },
    };
  },
};
