import type { Session, AreaWithContent, Concern } from '@tetherline/shared';

export function generateMarkdownDigest(
  session: Session,
  areas: AreaWithContent[],
  concerns: Concern[],
): string {
  const sections: string[] = [];

  sections.push(`# Code Review: ${session.repoName}`);
  sections.push(`**Period**: ${session.sinceDate} — ${session.untilDate}`);
  sections.push(`**Commits**: ${session.totalCommits} | **Areas**: ${areas.length} | **Observations**: ${concerns.length}`);
  sections.push('');

  if (session.summary) {
    sections.push('## Summary');
    sections.push(session.summary);
    sections.push('');
  }

  for (const area of areas) {
    sections.push(`## ${area.name}`);
    sections.push('');
    sections.push(area.description);
    sections.push('');
    sections.push(`*${area.significance} · ${area.commitHashes.length} commits · ${area.affectedFiles.length} files*`);
    sections.push('');

    // Key narration points
    if (area.narrationSegments.length > 0) {
      sections.push('### Changes');
      sections.push('');
      for (const segment of area.narrationSegments) {
        sections.push(`- ${segment.text}`);
        if (segment.visualCue.type === 'show_code' && segment.visualCue.code) {
          sections.push('');
          sections.push(`\`\`\`${segment.visualCue.language ?? ''}`);
          sections.push(segment.visualCue.code);
          sections.push('```');
          sections.push('');
        }
      }
      sections.push('');
    }

    // Files changed
    if (area.affectedFiles.length > 0) {
      sections.push('### Files');
      sections.push('');
      for (const file of area.affectedFiles.slice(0, 20)) {
        sections.push(`- \`${file}\``);
      }
      if (area.affectedFiles.length > 20) {
        sections.push(`- *...and ${area.affectedFiles.length - 20} more*`);
      }
      sections.push('');
    }

    // Area concerns
    const areaConcerns = concerns.filter(c => c.areaId === area.id);
    if (areaConcerns.length > 0) {
      sections.push('### Observations');
      sections.push('');
      for (const c of areaConcerns) {
        const icon = c.severity === 'critical' ? '!!!' : c.severity === 'warning' ? '!!' : 'i';
        sections.push(`- **[${icon}] ${c.title}**: ${c.description}`);
      }
      sections.push('');
    }
  }

  // Cross-cutting concerns
  const crossCutting = concerns.filter(c => !c.areaId);
  if (crossCutting.length > 0) {
    sections.push('## Cross-Cutting Concerns');
    sections.push('');
    for (const c of crossCutting) {
      sections.push(`### ${c.title} (${c.severity})`);
      sections.push('');
      sections.push(c.description);
      sections.push('');
      if (c.affectedFiles.length > 0) {
        sections.push('**Affected files:**');
        for (const file of c.affectedFiles) {
          sections.push(`- \`${file}\``);
        }
        sections.push('');
      }
    }
  }

  sections.push('---');
  sections.push(`*Generated by Tetherline on ${new Date().toISOString().split('T')[0]}*`);

  return sections.join('\n');
}
