import type { Session, AreaWithContent, Concern } from '@interactive-reviewer/shared';

export function generateRevealSlides(
  session: Session,
  areas: AreaWithContent[],
  concerns: Concern[],
): string {
  const slides: string[] = [];

  // Title slide
  slides.push(slide(`
    <h1>${escapeHtml(session.repoName)}</h1>
    <h3>Code Review: ${escapeHtml(session.sinceDate)} to ${escapeHtml(session.untilDate)}</h3>
    <p>${session.totalCommits} commits across ${areas.length} areas</p>
  `));

  // Summary slide
  if (session.summary) {
    slides.push(slide(`
      <h2>This Week at a Glance</h2>
      <p>${escapeHtml(session.summary)}</p>
    `));
  }

  // Per-area slide groups (vertical slides in Reveal.js)
  for (const area of areas) {
    const areaSlides: string[] = [];

    // Area title
    areaSlides.push(`
      <section>
        <h2>${escapeHtml(area.name)}</h2>
        <p>${escapeHtml(area.description)}</p>
        <p class="meta">${area.commitHashes.length} commits · ${area.affectedFiles.length} files · ${area.significance}</p>
      </section>
    `);

    // Narration segments with code
    for (const segment of area.narrationSegments) {
      if (segment.visualCue.type === 'show_code' && segment.visualCue.code) {
        areaSlides.push(`
          <section>
            <h3>${escapeHtml(segment.visualCue.filePath ?? '')}</h3>
            <pre><code class="language-${escapeHtml(segment.visualCue.language ?? 'text')}">${escapeHtml(segment.visualCue.code)}</code></pre>
            <aside class="notes">${escapeHtml(segment.text)}</aside>
          </section>
        `);
      } else if (segment.visualCue.type === 'show_diff' && segment.visualCue.filePath) {
        areaSlides.push(`
          <section>
            <h3>${escapeHtml(segment.visualCue.filePath)}</h3>
            <p>${escapeHtml(segment.text)}</p>
          </section>
        `);
      }
    }

    // Area concerns
    const areaConcerns = concerns.filter(c => c.areaId === area.id);
    if (areaConcerns.length > 0) {
      areaSlides.push(`
        <section>
          <h3>Observations</h3>
          <ul>
            ${areaConcerns.map(c => `<li><strong>[${escapeHtml(c.severity)}]</strong> ${escapeHtml(c.title)}: ${escapeHtml(c.description)}</li>`).join('\n')}
          </ul>
        </section>
      `);
    }

    slides.push(`<section>${areaSlides.join('\n')}</section>`);
  }

  // Cross-cutting concerns
  const crossCutting = concerns.filter(c => !c.areaId);
  if (crossCutting.length > 0) {
    slides.push(slide(`
      <h2>Cross-Cutting Concerns</h2>
      <ul>
        ${crossCutting.map(c => `<li><strong>[${escapeHtml(c.severity)}]</strong> ${escapeHtml(c.title)}: ${escapeHtml(c.description)}</li>`).join('\n')}
      </ul>
    `));
  }

  // Wrap-up
  slides.push(slide(`
    <h2>Summary</h2>
    <p>${session.totalCommits} commits reviewed across ${areas.length} areas</p>
    <p>${concerns.length} observations flagged</p>
    <p class="meta">Generated by Interactive Reviewer · ${new Date().toISOString().split('T')[0]}</p>
  `));

  return buildRevealHtml(session.repoName, slides.join('\n'));
}

function slide(content: string): string {
  return `<section>${content}</section>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildRevealHtml(title: string, slidesHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Code Review: ${escapeHtml(title)}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/reveal.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/theme/black.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/plugin/highlight/monokai.css">
  <style>
    :root { --r-background-color: #0a0a0f; --r-main-color: #e4e4ef; --r-heading-color: #e4e4ef; }
    .reveal { font-family: 'Inter', system-ui, sans-serif; }
    .reveal h1, .reveal h2, .reveal h3 { font-weight: 700; }
    .reveal pre { box-shadow: none; border: 1px solid #2a2a3a; border-radius: 12px; }
    .reveal code { font-size: 0.75em; }
    .reveal .meta { color: #8888a0; font-size: 0.7em; margin-top: 1em; }
    .reveal ul { text-align: left; }
    .reveal li { margin-bottom: 0.5em; font-size: 0.85em; }
  </style>
</head>
<body>
  <div class="reveal">
    <div class="slides">
      ${slidesHtml}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/reveal.js"><\/script>
  <script src="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/plugin/highlight/highlight.js"><\/script>
  <script>
    Reveal.initialize({
      hash: true,
      transition: 'slide',
      plugins: [RevealHighlight],
    });
  <\/script>
</body>
</html>`;
}
