import simpleGit from 'simple-git';
import type { Database } from '../db/database.js';
import type { AppConfig } from '../config.js';
import { v4 as uuid } from 'uuid';

export interface DigestEntry {
  repoName: string;
  repoPath: string;
  commitCount: number;
  summary: string;
  topChanges: string[];
}

export interface Digest {
  id: string;
  generatedAt: string;
  periodStart: string;
  periodEnd: string;
  entries: DigestEntry[];
  overallSummary: string;
}

export async function generateDigest(db: Database, config: AppConfig): Promise<Digest> {
  const repos = db.getRepoRepo().getAll();
  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 86400000);

  const entries: DigestEntry[] = [];

  for (const repo of repos) {
    try {
      const git = simpleGit(repo.path);
      const log = await git.log({ '--since': weekAgo.toISOString() } as any);

      if (log.total === 0) {
        entries.push({
          repoName: repo.name,
          repoPath: repo.path,
          commitCount: 0,
          summary: 'No changes this week.',
          topChanges: [],
        });
        continue;
      }

      const authors = [...new Set(log.all.map(c => c.author_name))];
      const topChanges = log.all.slice(0, 5).map(c => c.message.split('\n')[0]);

      entries.push({
        repoName: repo.name,
        repoPath: repo.path,
        commitCount: log.total,
        summary: `${log.total} commits from ${authors.join(', ')}`,
        topChanges,
      });
    } catch {
      entries.push({
        repoName: repo.name,
        repoPath: repo.path,
        commitCount: 0,
        summary: 'Could not analyze this repo.',
        topChanges: [],
      });
    }
  }

  const totalCommits = entries.reduce((s, e) => s + e.commitCount, 0);
  const activeRepos = entries.filter(e => e.commitCount > 0);
  const overallSummary = activeRepos.length > 0
    ? `${totalCommits} commits across ${activeRepos.length} repo${activeRepos.length !== 1 ? 's' : ''} this week.`
    : 'Quiet week across all repos.';

  const digest: Digest = {
    id: uuid(),
    generatedAt: now.toISOString(),
    periodStart: weekAgo.toISOString(),
    periodEnd: now.toISOString(),
    entries,
    overallSummary,
  };

  // Store in DB
  db.getRawDb().prepare(
    'INSERT INTO digest_history (id, generated_at, period_start, period_end, content, delivery_status) VALUES (?, ?, ?, ?, ?, ?)'
  ).run(digest.id, digest.generatedAt, digest.periodStart, digest.periodEnd, JSON.stringify(digest), 'generated');

  return digest;
}

export function formatDigestAsMarkdown(digest: Digest, appUrl: string): string {
  const lines: string[] = [];
  lines.push(`# Weekly Code Review Digest`);
  lines.push(`*${new Date(digest.periodStart).toLocaleDateString()} — ${new Date(digest.periodEnd).toLocaleDateString()}*`);
  lines.push('');
  lines.push(digest.overallSummary);
  lines.push('');

  for (const entry of digest.entries) {
    lines.push(`## ${entry.repoName}`);
    lines.push(entry.summary);
    if (entry.topChanges.length > 0) {
      lines.push('');
      for (const change of entry.topChanges) {
        lines.push(`- ${change}`);
      }
    }
    if (entry.commitCount > 0) {
      lines.push('');
      lines.push(`[Start walkthrough](${appUrl}?repo=${encodeURIComponent(entry.repoPath)}&mode=updates)`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Interactive Reviewer*');
  return lines.join('\n');
}

export function formatDigestAsHtml(digest: Digest, appUrl: string): string {
  const entries = digest.entries.map(entry => `
    <div style="margin-bottom: 24px; padding: 16px; border: 1px solid #2a2a3a; border-radius: 12px;">
      <h2 style="margin: 0 0 8px 0; font-size: 18px;">${entry.repoName}</h2>
      <p style="color: #888; margin: 0 0 8px 0;">${entry.summary}</p>
      ${entry.topChanges.length > 0 ? `<ul style="margin: 8px 0; padding-left: 20px; color: #aaa;">${entry.topChanges.map(c => `<li>${c}</li>`).join('')}</ul>` : ''}
      ${entry.commitCount > 0 ? `<a href="${appUrl}?repo=${encodeURIComponent(entry.repoPath)}&mode=updates" style="color: #6366f1; text-decoration: none;">Start walkthrough &rarr;</a>` : ''}
    </div>
  `).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Weekly Digest</title></head>
<body style="background: #0a0a0f; color: #e4e4ef; font-family: system-ui; max-width: 600px; margin: 0 auto; padding: 24px;">
  <h1 style="font-size: 24px;">Weekly Code Review Digest</h1>
  <p style="color: #888;">${new Date(digest.periodStart).toLocaleDateString()} &mdash; ${new Date(digest.periodEnd).toLocaleDateString()}</p>
  <p style="font-size: 16px; margin-bottom: 24px;">${digest.overallSummary}</p>
  ${entries}
  <hr style="border-color: #2a2a3a; margin: 24px 0;">
  <p style="color: #666; font-size: 12px;">Generated by Interactive Reviewer</p>
</body></html>`;
}
